package com.bot.business_through_awareness.model;

public enum UserState {
    START,
    CATEGORY_SELECTED,
    WAITING_FOR_QUESTION,
    ADMIN_MODE,
    ADMIN_ADDING_CATEGORY,
    ADMIN_SELECTING_GROUP,
    ADMIN_EDITING_CATEGORY,
    ADMIN_ADDING_GROUP,
    ADMIN_ADDING_EXECUTOR,
    ADMIN_SELECTING_GROUP_FOR_EXECUTOR,
    EXECUTOR_ANSWERING_QUESTION
}

